2024-09-20 22:17:15,487 - testing_logging.main - INFO - Starting the main function
2024-09-20 22:17:15,487 - testing_logging.module2 - INFO - This is a info message from module2
2024-09-20 22:17:15,487 - testing_logging.module2 - WARNING - This is a warning message from module2
2024-09-20 22:17:15,487 - testing_logging.module2 - ERROR - This is an error message from module2
just printing here
Traceback (most recent call last):
  File "/Users/ct5868/code/testing-nested-logging/outer_and_inner_logger.py", line 10, in <module>
    testing_logging.main.main()
  File "/Users/ct5868/code/testing-nested-logging/src/testing_logging/main.py", line 20, in main
    raise e
  File "/Users/ct5868/code/testing-nested-logging/src/testing_logging/main.py", line 14, in main
    module2.another_function()
  File "/Users/ct5868/code/testing-nested-logging/src/testing_logging/module2.py", line 11, in another_function
    0/0
    ~^~
ZeroDivisionError: division by zero
